// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Monitor>>
abstract class Monitor implements RustOpaqueInterface {
  Future<String> deviceDescription();

  Future<String> deviceName();

  Future<String> devicePath();

  Future<String> displayName();

  Future<String> friendlyDeviceName();

  Future<int> getBrightness();

  static Future<List<MonitorResult>> getMonitors() =>
      RustLib.instance.api.crateApiMonitorsMonitorGetMonitors();

  Future<void> setBrightness({required int value});
}

class MonitorResult {
  final Monitor? success;
  final String? fail;

  const MonitorResult({this.success, this.fail});

  @override
  int get hashCode => success.hashCode ^ fail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          fail == other.fail;
}
