// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(double?, bool) loadSettings() =>
    RustLib.instance.api.crateApiNightlightLoadSettings();

void setWarmth({required double strength}) =>
    RustLib.instance.api.crateApiNightlightSetWarmth(strength: strength);

void setActive({required bool isActive}) =>
    RustLib.instance.api.crateApiNightlightSetActive(isActive: isActive);
